Create docker-image.yml
MS-PINPOINT/mindGlide pull request #24
Opened 2024-04-29 09:18 UTC by phiphi0815

Builds and pushes new docker image when pushed to master or pull request.

2024-04-29 12:19 UTC, jstutters commented
@phiphi0815 might want to try adding some caching to this or add an issue to work on that later.

2024-04-29 12:22 UTC, armaneshaghi requested changes
Outstanding a clear container build

2024-05-08 12:05 UTC, armaneshaghi commented
Happy to merge when all checks (under `checks` tab) pass with no error

2024-05-09 09:03 UTC, phiphi0815 commented
Github hosted runners run out of space due to large docker image of mindglide when automatically updating dockerhub with github actions.

Solution:
Currently I will manually push updated docker images to dockerhub. In the future we can think about self-hosted runners.

2024-05-09 09:44 UTC, armaneshaghi commented
@jstutters is it worth setting up a Docker as a self hosted runner within the Unit? The config looks relatively straightforward

2024-05-09 12:08 UTC, armaneshaghi commented
spoke @jstutters and @phiphi0815 

- [ ] @jstutters to push a branch to clean up docker to be less than 14GB 
- [ ] @phiphi0815 to retry with a pruned image from Jon's work

2024-05-16 16:57 UTC, phiphi0815 commented
I have removed the old models (to prune the image and save space) on the branch `remove_old_models`. 

Branch: [remove_old_models](https://github.com/MS-PINPOINT/mindGlide/tree/remove_old_models)

The Github hosted runner is still running out of space after removing the old models. (Docker image size previously: 18.6GB; currently: 17.2GB

2024-05-16 17:05 UTC, jstutters commented
@phiphi0815 does it improve things if you merge master into remove_old_models?  Probably also need to edit https://github.com/MS-PINPOINT/mindGlide/blob/1f105276b1c6d21c789b44469ae8a80bfb792f72/Dockerfile#L21 so it uses a commit that has the single model file.

2025-11-20 14:26 UTC, closed without merging